openapi: "3.0.2"
info:
  title: api.boenderegistret.se which is for booking management and access control on the apartments and laundries. Used by DinBox app
  version: "1.0"
servers:
  - url: https://api.boenderegistret.se
    description: Used for the rest of the api
paths:
  /oauth/token:
    servers:
      - url: https://accounts.dinbox.se
    post:
      summary: get token
      operationId: getToken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                grant_type:
                  type: string
                client_id:
                  type: string
                  example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
                client_secret:
                  type: string
                api_key:
                  type: string
                  example: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
                  refresh_token:
                    type: string
                  expires_in:
                    type: integer
  /residential/people:
    post:
      summary: Get default info
      description: Get default info
      operationId: getPerson
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    addressId:
                      type: integer
                    firstName:
                      type: string
                    lastName:
                      type: string
                    internalApartmentNumber:
                      type: string
                    officialApartmentNumber:
                      type: string
                    floor:
                      type: integer
                    moveIn:
                      type: string
                    moveOut:
                      type: string
                    language:
                      type: string
                    email:
                      type: string
                    secretNotes:
                      type: string
                    visibility:
                      type: integer
                    personalCode:
                      type: string
                    importId:
                      type: string
                    contractId:
                      type: string
                    showInLogs:
                      type: integer
                    bookingAdmin:
                      type: string
                    created:
                      type: string
                    createdBy:
                      type: integer
                    updated:
                      type: string
                    updatedBy:
                      type: string
                    accountRelationKey:
                      type: string
                    addressName:
                      type: string
                    zip:
                      type: string
                    city:
                      type: string
                    organisationId:
                      type: integer
                    organisationName:
                      type: string
                    isBetaEnabled:
                      type: integer
                    keys:
                      type: object
                      properties:
                        serial:
                          type: string
                        label:
                          type: string
                        restricted:
                          type: string
                    id:
                      type: integer
                    phoneNumbers:
                      type: object
                      properties:
                        description:
                          type: string
                        priority:
                          type: integer
                    personGroups:
                      type: array
                      items:
                        type: string
                    connectedAccountInfo:
                      type: object
                      properties:
                        created_at:
                          type: string
                        updated_at:
                          type: string
                        account_id:
                          type: string
                        person_id:
                          type: integer
  /residential/booking/schedules:
    get:
      summary: Get schedules
      description: Get schedules
      operationId: getSchedules
      parameters:
        - name: personId
          in: query
          description: personId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    id:
                      type: integer
  /residential/booking/reservations:
    post:
      summary: Book a reservation
      description: Book a reservation
      operationId: bookReservation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                personId:
                  type: integer
                scheduleId:
                  type: integer
                date:
                  type: string
                slotNumber:
                  type: integer
      responses:
        200:
          description: OK
    get:
      summary: Get reservations
      description: Get reservations
      operationId: getReservations
      parameters:
        - name: personId
          in: query
          description: personId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    status:
                      type: string
                    bookedOn:
                      type: string
                    personId:
                      type: integer
                    wallpadDeviceId:
                      type: string
                    date:
                      type: string
                    slotNumber:
                      type: integer
                    scheduleId:
                      type: integer
                    facilityId:
                      type: integer
                    facilityName:
                      type: string
                    time:
                      type: object
                      properties:
                        start:
                          type: string
                        end:
                          type: string
  /residential/booking/reservations/{reservationId}:
    delete:
      summary: Delete a reservation
      description: Delete a reservation
      operationId: deleteReservation
      parameters:
        - name: reservationId
          in: path
          description: reservationId
          required: true
          schema:
            type: integer
        - name: personId
          in: query
          description: personId
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK